app:
  myport: ${PORT:0}

spring:
  application:
    name: desconto-service

server:
  port: ${app.myport}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}